kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
  - apt install libssl-dev openssl pkg-config git -y
  - git clone https://github.com/sozu-proxy/sozu.git
  - cd sozu
  - git checkout 0.13.6 
  - cd bin && cargo build --release --features use-openssl
  - mkdir /release/bin
  - cp build/release/{sozu,sozuctl} /release/bin  
  volumes:
  - name: release 
    path: /release 

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
      - /release/bin/*
  volumes:
  - name: release 
    path: /release 
  when:
    event: tag
    
volumes:
- name: release
  temp: {}